package de.sebastianruziczka.cobolunit;

public class CobolUnitMetaKeys {
	public static String ABSOLUTE_FIXED_UNITTEST_PATH = "COBOLUNIT_ABSOLUTE_FIXED_UNITTEST_PATH";
	public static String BUILD_TEST_EXECFILE_PATH = "COBOLUNIT_BUILD_TEST_EXECFILE_PATH";
	public static String BUILD_TEST_EXEC_LOG_PATH = "COBOLUNIT_BUILD_TEST_EXEC_LOG_PATH";
	public static String BUILD_TEST_PRECOMPILER_LOG_PATH = "COBOLUNIT_BUILD_TEST_PRECOMPILER_LOG_PATH";
}
